version: '3'
services:
  app:
    image: node:18
    restart: always
    ports:
      - "9002:3000"
    volumes:
      - .:/app
    entrypoint: bash -c "cd /app && HOST=0.0.0.0 PORT=3000 node ./dist/server/entry.mjs"